#spring.application.name=codeGenerator
## First database configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/places_official
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Docker container configuration
spring.datasource.url=jdbc:mysql://localhost:3307/places_official
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect